version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/aztecweb.net
permissions:
  - object: /var/www/aztecweb.net
    owner: ubuntu
hooks:
  AfterInstall:
    - location: bin/install
      timeout: 180
